# Generated by Django 5.0.2 on 2025-03-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_qrsession_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='paired_device',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eşleştirilmiş Cihaz Kimliği'),
        ),
    ]
