# Generated by Django 5.1.4 on 2025-04-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_paired_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='paired_device',
        ),
    ]
